### ISSUE TITLE
是否接受PR

### ISSUE THREAD

**Issue by LinkTechTips** [star-reader/Onlne-fly-Map-v1---v1#1]
我打算在贵平台初版地图上进行UI以及后端优化改进 不知是否接受PR (?)

**Comment by star-reader** [comment]
可以的，这个地图其实现在已经不用了，就是不知道别人能不能用上所以发出来的，可以进行修改

**Comment by LinkTechTips** [comment]
> 可以的，这个地图其实现在已经不用了，就是不知道别人能不能用上所以发出来的，可以进行修改

收到 由于改了平台名称等 项目完成后会单开一个branch并PR到repo
